### ISSUE TITLE
MainActivity Switch DarkMode Crash

### ISSUE THREAD

**Issue by li-lance** [material-components/material-components-android-examples#52]
```2020-07-30 15:51:05.720 16808-16808/com.materialstudies.owl E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.materialstudies.owl, PID: 16808
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.materialstudies.owl/com.materialstudies.owl.ui.MainActivity}: java.lang.IllegalArgumentException: width and height must be > 0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3895)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4074)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6046)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5936)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8347)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
     Caused by: java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1257)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1224)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1174)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1135)
        at androidx.core.view.ViewKt.drawToBitmap(View.kt:181)
        at androidx.core.view.ViewKt.drawToBitmap$default(View.kt:177)
        at com.materialstudies.owl.util.ViewExtensionsKt.show(ViewExtensions.kt:194)
        at com.materialstudies.owl.ui.MainActivity$onCreate$1$1.onDestinationChanged(MainActivity.kt:44)
        at androidx.navigation.NavController.addOnDestinationChangedListener(NavController.java:204)
        at com.materialstudies.owl.ui.MainActivity.onCreate(MainActivity.kt:42)
        at android.app.Activity.performCreate(Activity.java:8085)
        at android.app.Activity.performCreate(Activity.java:8073)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3868)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4074) 
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6046) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5936) 
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8347) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055) 
```

**Comment by li-lance** [comment]
```
navController.addOnDestinationChangedListener { _, destination, _ ->
          when (destination.id) {
            R.id.components, R.id.helper -> bottomNavigationView.show()
            else -> bottomNavigationView.hide()
          }
        }
```

to
  ```
lifecycleScope.launchWhenResumed {
        navController.addOnDestinationChangedListener { _, destination, _ ->
          when (destination.id) {
            R.id.components, R.id.helper -> bottomNavigationView.show()
            else -> bottomNavigationView.hide()
          }
        }
      }
```
